version: 0.2
env:
  #shell: bash
  varibales:
    CODEBUILD_WEBHOOK_EVENT: events
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
   # runtime-versions:
     # java: corretto11
  build:
    commands:
      - |-
        event : "$CODEBUILD_WEBHOOK_EVENT"  
         if [ "$events" -eq PULL_REQUEST_CREATED ]; then
            echo "run my command `date`"
         fi
