version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    runtime-versions:
      java: corretto11
 
  build:
    commands:
      - |
        
        set -e
        if [[ " ${CODEBUILD_WEBHOOK_EVENT} " == "PULL_REQUEST_CREATED" ]]; then
          # Iterate only through BRANCH_NAME directory
          echo "before merge 'date'
        else
          # Iterate through both dev and prod directories
          echo "after merge"
        fi
      

