version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
   # runtime-versions:
     # java: corretto11
  build:
    commands:
      - |-
        set +e
        echo "$CODEBUILD_WEBHOOK_EVENT"  
        ev=$?
         if [ "$ev" -eq "0" ]; then
            echo "run my command `date`"
         fi
