version: 0.2
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/aws-build-sample-maven-project-0.0.1-SNAPSHOT.jar

    ##
