version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven... 
  build:
    commands:
       - echo "${CODEBUILD_WEBHOOK_EVENT}"
       - |
         if [[ "${CODEBUILD_WEBHOOK_EVENT}" = 'PULL_REQUEST_MERGED' ]]; then
           echo "tes1"
         fi
       - |
         if [[ "${CODEBUILD_WEBHOOK_EVENT}" = 'PULL_REQUEST_CREATED' ]]; then
            echo "test2"
         fi
