version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
   # runtime-versions:
     # java: corretto11  
   build:
    commands:
      - |-
        ev=$CODEBUILD_WEBHOOK_EVENT
        echo $ev
         if [ "$ev" = "PULL_REQUEST_MERGED" ]; then
            echo "run my command `date`"
         fi
   
