version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    runtime-versions:
      java: corretto11
  build:
    commands:
      - |-
        echo "$CODEBUILD_WEBHOOK_EVENT"  
         if [ "$CODEBUILD_WEBHOOK_EVENT" -eq "PULL_REQUEST_CREATED" ]; then
            echo "run my command `date`"
         fi
