version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
   build:
    commands:
      - |-
        ev=$CODEBUILD_WEBHOOK_EVENT
        echo $ev
         if [ "$ev" = "PULL_REQUEST_CREATED" ]; then
            echo "run my command `date`"
         fi
   
