version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
   # runtime-versions:
     # java: corretto11
  build:
    commands:
      - echo post Build completed on `date`
      
  post_build:
    commands:
      - |-
        #set +e
        #echo "$CODEBUILD_WEBHOOK_EVENT"  
        ev=$CODEBUILD_WEBHOOK_EVENT
        echo $ev
         if [ "$ev" = "PULL_REQUEST_MERGED" ]; then
            echo "run my command `date`"
            ./push.sh
         fi
   
