version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    runtime-versions:
      java: corretto11
  build:
    commands:
      - |
        if [[ " ${CODEBUILD_WEBHOOK_EVENT} " == "PULL_REQUEST_CREATED" ]]; then
          
          echo "before merge 'date'
        else
          
          echo "after merge"
        fi
      

